Handle insert video request
yibane-yibane/bionic-eye pull request #3
Opened 2021-07-04 08:16 UTC by yibane-yibane

2021-07-04 13:32 UTC, MayoG requested changes

2021-07-04 13:32 UTC, MayoG commented on data_base/data_models/Frame.py
> +    id = Column(String, primary_key=True)
Why changing from Integer to String ?

2021-07-04 13:32 UTC, MayoG commented on data_base/SQLAlchemy.py
> +            self.db.session.merge(table_instance)
Why are you using merge ?
please make sure that you understand what the function does.

2021-07-04 13:32 UTC, MayoG commented on data_base/data_models/Frame.py
> +    def __init__(self, frame_id: str, video_id: str, os_path: str, index: int):
You don't have to create the __init__ function, it generates automatically.
And the id of the frame should be generated automatically.

2021-07-04 13:32 UTC, MayoG commented on data_base/data_models/Metadata.py
> +    def __init__(self, metadata_id: str, fov: float, azimuth: float, elevation: float, tag: bool):
> You don't have to create the init function, it generates automatically.
And the id of the metadata should be generated automatically.

2021-07-04 13:32 UTC, MayoG commented on data_base/data_models/Video.py
> +    def __init__(self, video_id: str, observation_name: str, os_path: str, number_of_frames: int):
> You don't have to create the init function, it generates automatically.
And the id of the video should be generated automatically.

2021-07-04 13:32 UTC, MayoG commented on object_store/azure_handler.py
> +        blob_client = self.blob_service_client.get_blob_client(container=self.container_name, blob=path+file_name)
What happens if the container doesn't exist ?

2021-07-04 13:32 UTC, MayoG commented on logger/logger.py
> +class Logger(metaclass=Singleton):
The singleton metaclass here is useless.
If you decide to use only static variables and not instancing a new object of the logger then it shouldn't be singleton.

If you decide to use the singleton, please transfer the lines to class methods.

2021-07-04 13:32 UTC, MayoG commented on object_store/AzureConfig.py
> +class AzureConfig(metaclass=Singleton):
Why instancing it as a static class and not as an environment variable.

2021-07-04 13:32 UTC, MayoG commented on object_store/azure_handler.py
> +from .AzureConfig import AzureConfig
Please change the name of the folder to object storage instead of store.

2021-07-04 13:32 UTC, MayoG commented on object_store/azure_handler.py
> +class AzureBlobHandler:
The name or purpose of the class is not good enough.
If its an azure blob handler give more functionality to the container name.

2021-07-04 13:32 UTC, MayoG commented on utils/frame_utils.py
> +    return os.path.join("frames", video_name, f'frame{index}.jpg')
why having the frames folder before the video name folder ?

2021-07-04 13:32 UTC, MayoG commented on utils/metadata_utils.py
> +def extract_video_to_frames(path):
Shouldn't be in the metadata utils.

2021-07-04 13:32 UTC, MayoG commented on utils/metadata_utils.py
> +    cv2.destroyAllWindows()
Why executing DestoryAllWindows?

2021-07-04 13:32 UTC, MayoG commented on utils/metadata_utils.py
> +    return [metadata for metadata in metadatas if metadata.id == metadata_id]
Why do you need these functions ?

2021-07-05 08:41 UTC, yibane-yibane commented on data_base/data_models/Frame.py
> +    id = Column(String, primary_key=True)
Because using uuid which is string for creating frame id.

2021-07-05 08:46 UTC, yibane-yibane commented on data_base/SQLAlchemy.py
> +            self.db.session.merge(table_instance)
Using merge to ignore the conflict in metadata table and avoid duplicated metadata.
The other choice is to query the db for each metadata model when created if its already exists, which leads a lot of requests to db.

2021-07-06 08:16 UTC, MayoG commented on data_base/data_models/Frame.py
> +    id = Column(String, primary_key=True)
Why using uuid for generating the ids ?
The database will do it better and there is no reason to not use it IMO.

2021-07-11 09:10 UTC, closed without merging