Frame path by index and video
yibane-yibane/bionic-eye pull request #8
Opened 2021-07-26 13:38 UTC by yibane-yibane

2021-07-26 18:19 UTC, MayoG requested changes

2021-07-26 18:19 UTC, MayoG commented on flask_app/FlaskApp.py
>          self.app.add_url_rule('/upload_video', view_func=self.upload_video, methods=['POST'])
Please read again about the methods (Get, Post, Put and Delete and see what is good for each route)
Also please rewrite the url routes to something more dynamic.

2021-07-26 18:19 UTC, MayoG commented on flask_app/FlaskApp.py
> +        frame_path = DataModelTransactions.get_frame_path_by_index_and_video_id(video_id, frame_index)
What hapenns if there are no frame paths with this index and video id ?

2021-07-27 08:58 UTC, yibane-yibane commented on flask_app/FlaskApp.py
> +        frame_path = DataModelTransactions.get_frame_path_by_index_and_video_id(video_id, frame_index)
So the user get [], eventually the user get what he asks, If there is problem with thw response its not my problem.

2021-07-29 07:22 UTC, MayoG approved these changes

2021-07-29 11:33 UTC, merged